### ISSUE TITLE
 تداخل در نصب 

### ISSUE THREAD

**Issue by NoRRt** [TheyCallMeSecond/Argo#1]
سلام. مثل اینکه اسکریپت Argo با اسکریپت [singbox](https://github.com/TheyCallMeSecond/config-examples)
موقع نصب Argo به مشکل بر میخوره.
احتمال داره بخاطر اینکه Warp اسکریپت  [singbox](https://github.com/TheyCallMeSecond/config-examples) نصب کردم تداخل ایجاد کنه

![Screenshot_20231223_062310_Termius](https://github.com/TheyCallMeSecond/Argo/assets/4822035/7c4bc652-7043-43d2-ab53-f4f997128694)

**Comment by TheyCallMeSecond** [comment]
نه تداخلی نداره،همون بالا رو نگاه کنی داخل اسکرین شاتت یه لینک داده گفته از طریقه اون لینک باید لاگین کنی به اکانت کلاودفلرت و انتخاب کنی که از کدوم دامینت استفاده کنه واسه ساخت تانل.رو لینک کلیک کن و ادامه بده

**Comment by NoRRt** [comment]
مرسی..
